# Generated by Django 6.0.3 on 2026-03-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festive_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
