# Generated by Django 6.0.3 on 2026-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_sitesetting_booking_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
