# Generated by Django 6.0.3 on 2026-03-07 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_adults_booking_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_ref',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
